version: '2'

services:
    db:        
        image: postgres
        env_file: ./postgres/envars
        volumes:
          - ./postgres:/usr/bin
        #entrypoint: /usr/bin/init-pg.sh
    gogs:
        build: gogs
        volumes:
          - ./gogs:/data
        ports:
          - "31337:3000"
        depends_on:
          - db
