version: '2'

services:
    db:
        image: postgres
    gogs:
        image: gogs/gogs
        volumes:
          - ./gogs:/data
        ports:
          - "31337:3000"
        depends_on:
          - db
