version: '2'

services:
    db:        
        build: postgres
        env_file: environment
        volumes:
          - ./postgres:/usr/bin
        
    gogs:
        build: gogs
        volumes:
          - ./gogs:/data
        env_file: environment
        restart: always
        ports:
          - "2022:22"
        depends_on:
          - db

    drone:
        image: drone/drone
        volumes:
          - ./drone:/var/lib/drone
          - /var/run/docker.sock:/var/run/docker.sock
        env_file: environment 
        restart: always
        depends_on:
          - db
          - gogs

    nginx:
        build: nginx
        ports:
          - "80:80"
        depends_on:
          - gogs
          - drone
