version: '2'

services:
    db:        
        build:
          context: ./postgres
        env_file: envars
        volumes:
          - ./postgres:/usr/bin
        
    gogs:
        build: gogs
        volumes:
          - ./gogs:/data
        ports:
          - "31337:3000"
        depends_on:
          - db
