version: '2'

services:
    db:        
        build:
          context: ./postgres
        env_file: environment
        volumes:
          - ./postgres:/usr/bin
        
    gogs:
        build: gogs
        volumes:
          - ./gogs:/data
        ports:
          - "31337:3000"
        depends_on:
          - db

    drone:
        image: drone/drone
        volumes:
          - ./drone:/var/lib/drone
          - /var/run/docker.sock:/var/run/docker.sock
        env_file: environment 
        restart: always
        ports:
          - "31338:8000"
        depends_on:
          - db
          - gogs
