#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $DRONE_DB_USERNAME;
    ALTER USER $DRONE_DB_USERNAME WITH PASSWORD '$DRONE_DB_PASSWORD';
    CREATE DATABASE $DRONE_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $DRONE_DB_NAME TO $DRONE_DB_USERNAME
EOSQL
