#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE USER $GOGS_DB_USERNAME;
    ALTER USER $GOGS_DB_USERNAME WITH PASSWORD '$GOGS_DB_PASSWORD';
    CREATE DATABASE $GOGS_DB_NAME;
    GRANT ALL PRIVILEGES ON DATABASE $GOGS_DB_NAME TO $GOGS_DB_USERNAME
EOSQL
